[[gauges]]
id = 0
style = "Arc"
range = { min = -20.0, max = 40.0 }
signal = { name = "Temperature (C°)" }

[[gauges]]
id = 1
style = "Circle"
range = { min = 0.0, max = 100.0 }
signal = { name = "Speed (knots)" }

[[gauges]]
id = 2
style = "Protractor"
range = { min = 0.0, max = 360.0 }
signal = { name = "Angle (deg)" }
