[network]
addr = "127.0.0.1:9999"

[dashboard]
age_indicator = true

[[gauges]]
id = 0
style = "Arc"
range = { min = -20.0, max = 40.0 }
signal = { name = "Temperature (C°)" }
format = { precision = 1 }

[[gauges]]
id = 1
style = "Circle"
range = { min = 0.0, max = 100.0 }
signal = { name = "Speed (knots)" }
format = { precision = 2 }

[[gauges]]
id = 2
style = "Protractor"
range = { min = 0.0, max = 360.0 }
signal = { name = "Angle (deg)" }

[[gauges]]
id = 3
style = "OnOff"
signal = { name = "Active" }
